version: "3"

services:
  redis:
    image: redis:alpine
  addok:
    build: 
      context: ./addok
      # If docker runs behind proxy
      #args:
        #http_proxy: 'http://proxy_ip:proxy_port'
        #https_proxy: 'http://proxy_ip:proxy_port'
    links:
      - redis
    ports:
      - 7878:7878
    volumes:
      - ./addok-data:/data
    environment:
      GUNICORN_WORKERS: 1
      GUNICORN_TIMEOUT: 60
